meta_product_name: "Christian Zamora"
meta_title: "Christian Zamora-Portfolio"
meta_description: "Christian Zamora, full stack developer portfolio web application"
meta_image: "chris_zam_pic.png" 
twitter_account: "@Xtianito"  